[settings]
requirements-in = requirements.txt
requirements-out = requirements-mxdev.txt
constraints-out = constraints-mxdev.txt
default-target = sources
default-install-mode = editable


; Local directories (symlinked into ./sources), no checkout needed.

[collective.travelstream]
url = collective.travelstream
vcs = fs
